apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dso-demo
  name: dso-demo
  annotations:
    container.apparmor.security.beta.kubernetes.io/dso-demo: runtime/default
    container.seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      containers:
      - image: inikolaou/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      automountServiceAccountToken: false
      serviceAccountName: dso-demo
      securityContext:
        seccompProfile:
          type: RunTimeDefault
        runAsGroup: 11000
      volumes:
      - name: tmp
        emptyDir: {}
status: {}
